name: Run Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: root
      DB_NAME: book_management_test
      DB_PORT: 3306
      
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: book_management_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p logs

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          timeout 30 bash -c 'until mysql -h127.0.0.1 -uroot -proot -e "SELECT 1"; do sleep 1; done'
          echo "MySQL is up and running!"

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

      - name: Run test coverage
        run: npm run test:coverage
        if: always()